## Numpy Guide for AI, Machine & Deep Learning
**This Notebook will cover the widely used Numpy operations on Vectors and Martices In Artificial Intelligence & Machine Learning.**

This notebook can be used as a reference and handly guide for both newcomers & Experienced in Machine Learning & AI.

## Load Modules

In [1]:
import numpy as np # linear algebra

## np.shape & np.reshape
**np.shape : Gives the shape of matrix/vector**
**np.reshape: Matrix/vector can be reshaoe to any size based on the no. of elements**

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9])  # convert the passed list to form array
print(x.shape)
x = x.reshape(9,1)    # reshape the array into a row vector
print(x)
print(x.shape)
x = x.reshape(1,9)    # reshape the array into a column vector
print(x)
print(x.shape)
x = x.reshape(3,3)    # reshape into a 3x3 matrix
print(x)
print(x.shape)

# rows and columns in the shape can be individually accessed as
print(x.shape[0])
print(x.shape[1])

(9,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(9, 1)
[[1 2 3 4 5 6 7 8 9]]
(1, 9)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
3
3


## Copy 1 numpy array into Another

In [2]:
x = np.array([1,2,3,4,5,6])
y = np.copy(x)
print(x,y)

y = 

[1 2 3 4 5 6] [1 2 3 4 5 6]


## Reshaping of Images
A coloured image is represented by a 3D array of shape (length,height,depth=3) where depth of 3 correponds to R,G, B color. However, when you read an image as the input of an algorithm you need to convert it to a vector of shape **(length∗height∗depth, 1)**. ie. you need to reshape the 3D array into a 1D vector

In [3]:
# Consider the below image of shape (3,3,3)
image = np.array([[[ 0.67826139,  0.29380381, 0.67826139],
        [ 0.90714982,  0.52835647, 0.90714982],
        [ 0.4215251 ,  0.45017551, 0.4215251]],

       [[ 0.92814219,  0.96677647, 0.92814219],
        [ 0.85304703,  0.52351845, 0.85304703],
        [ 0.19981397,  0.27417313, 0.19981397]],

       [[ 0.60659855,  0.00533165, 0.60659855],
        [ 0.10820313,  0.49978937, 0.10820313],
        [ 0.34144279,  0.94630077, 0.34144279]]])

print(image.shape)
new_shape = image.reshape(image.shape[0]*image.shape[1]*image.shape[2], 1)
print(new_shape)
print(new_shape.shape)

(3, 3, 3)
[[0.67826139]
 [0.29380381]
 [0.67826139]
 [0.90714982]
 [0.52835647]
 [0.90714982]
 [0.4215251 ]
 [0.45017551]
 [0.4215251 ]
 [0.92814219]
 [0.96677647]
 [0.92814219]
 [0.85304703]
 [0.52351845]
 [0.85304703]
 [0.19981397]
 [0.27417313]
 [0.19981397]
 [0.60659855]
 [0.00533165]
 [0.60659855]
 [0.10820313]
 [0.49978937]
 [0.10820313]
 [0.34144279]
 [0.94630077]
 [0.34144279]]
(27, 1)


## Adding a matrix with m rows and 1 column to another with 1 row and 1 column
**A Matrix is defined as a 2D array with Rows & Columns**
So,lets denote number of rows with m and
number of columns with n

**Below are the generalized formula for doing mathematical operation (add, subtract, multiply, divide) on 2 matrices**

Adding a matrix with m row and 1 column to another with 1 row and 1 column will result in adding each row of matrix m with 2nd matrix row
* **(m,1) + (1,1) = (m+1, 1)**
* **(m,1) * (1,1) = (mx1, 1)**
* **(m,1) / (1,1) = (m/1, 1)**
* **(m,1) - (1,1) = (m-1, 1)**

In [4]:
list1 = [1,2,3,4,5,6]
list2 = [10,20,30]

matrix1 = np.array(list1).reshape(6,1)      # 6 rows and 1 column
print(f"Matrix1 of size m,1 = \n{matrix1}")

matrix2 = np.array(list2[0]).reshape(1,1)
print(f"Matrix2 of size 1,1 = \n{matrix2}")

add_result = np.add(matrix1, matrix2)
print(f"Result m+1,1 = \n{add_result}")

mult_result = np.matmul(matrix1, matrix2)
print(f"Result mx1,1 = \n{mult_result}")

div_result = np.divide(matrix1, matrix2)
print(f"Result m/1,1 = \n{div_result}")

sub_result = np.subtract(matrix1, matrix2)
print(f"Result m-1,1 = \n{sub_result}")

Matrix1 of size m,1 = 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Matrix2 of size 1,1 = 
[[10]]
Result m+1,1 = 
[[11]
 [12]
 [13]
 [14]
 [15]
 [16]]
Result mx1,1 = 
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]
Result m/1,1 = 
[[0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]
 [0.6]]
Result m-1,1 = 
[[-9]
 [-8]
 [-7]
 [-6]
 [-5]
 [-4]]


## Adding a matrix with 1 row and n columns to another with 1 row and 1 column
**(1, n) + (1, 1) = (1, n+1)**

In [5]:
list1 = [1,2,3,4,5,6]
list2 = [10,20,30]

matrix1 = np.array(list1).reshape(1,6)     # 1 row and 6 columns
print(f"Matrix1 of size 1,m = \n{matrix1}")

matrix2 = np.array(list2[0]).reshape(1,1)
print(f"Matrix2 of size 1,1 = \n{matrix2}")

add_result = np.add(matrix1, matrix2)
print(f"Result 1,n+1 = \n{add_result}")

Matrix1 of size 1,m = 
[[1 2 3 4 5 6]]
Matrix2 of size 1,1 = 
[[10]]
Result 1,n+1 = 
[[11 12 13 14 15 16]]


## Adding a matrix with m rows and n columns to another with 1 row and n columns
**(m, n) + (1, n) = (m, n+n)**

In [6]:
list1 = [1,2,3,4,5,6]
list2 = [10,20,30]

matrix1 = np.array(list1).reshape(2,3)     # 2rows and 3 columns
print(f"Matrix1 of size m,n = \n{matrix1}")

matrix2 = np.array(list2).reshape(1,3)
print(f"Matrix2 of size 1,n = \n{matrix2}")

add_result = np.add(matrix1, matrix2)
print(f"Result m,n+n = \n{add_result}")

Matrix1 of size m,n = 
[[1 2 3]
 [4 5 6]]
Matrix2 of size 1,n = 
[[10 20 30]]
Result m,n+n = 
[[11 22 33]
 [14 25 36]]


## Adding a matrix with m rows and n columns to another with m rows and 1 column
**(m, n) + (m, 1) = (m+m, n)**

In [7]:
list1 = [1,2,3,4,5,6]
list2 = [10,20,30]

matrix1 = np.array(list1).reshape(3,2)     # 3 rows and 2 columns
print(f"Matrix1 of size m,n = \n{matrix1}")

matrix2 = np.array(list2).reshape(3,1)     # 3 rows and 1 column
print(f"Matrix2 of size 3,1 = \n{matrix2}")

add_result = np.add(matrix1, matrix2)
print(f"Result m+m,n = \n{add_result}")

Matrix1 of size m,n = 
[[1 2]
 [3 4]
 [5 6]]
Matrix2 of size 3,1 = 
[[10]
 [20]
 [30]]
Result m+m,n = 
[[11 12]
 [23 24]
 [35 36]]


## Adding a matrix with m rows and n columns to another with m rows and n columns
Then it will be any of 1 below
* **(m, n) + (m, n) = (m+m, n)**
* **(m, n) + (m, n) = (m, n+n)**
1. Both will have same results

In [8]:
list1 = [1,2,3,4,5,6]
list2 = [10,20,30,40,50,60]

matrix1 = np.array(list1).reshape(3,2)     # 3 rows and 2 columns
print(f"Matrix1 of size m,n = \n{matrix1}")

matrix2 = np.array(list2).reshape(3,2)     # 3 rows and 2 column
print(f"Matrix2 of size 3,2 = \n{matrix2}")

add_result = np.add(matrix1, matrix2)
print(f"Result m+m,n+n = \n{add_result}")

Matrix1 of size m,n = 
[[1 2]
 [3 4]
 [5 6]]
Matrix2 of size 3,2 = 
[[10 20]
 [30 40]
 [50 60]]
Result m+m,n+n = 
[[11 22]
 [33 44]
 [55 66]]


## Dot multiplication of 2 Vectors & Matrices

In [9]:
# Dot operation on 2 vectors
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
result = np.dot(x,y)
print(result)   # 1x5 + 2x6 + 3x7 + 4x8 = 70

# Dot operation on 2 matrices
x = np.array([1,2,3,4]).reshape(2,2)
print(f"x = \n{x}")
y = np.array([5,6,7,8]).reshape(2,2)
print(f"y = \n{y}")
result = np.dot(x,y)

# Output calculation:
# 1x5 + 2x7 = 19  ie. row 1 to column 1
# 3x5 + 4x7 = 43  ie. row 2 to column 1
# 1x6 + 2x8 = 22  ie. row 1 to column 2
# 3x6 + 4x8 = 50  ie. row 2 to column 2
print(f"result = \n{result}")   

70
x = 
[[1 2]
 [3 4]]
y = 
[[5 6]
 [7 8]]
result = 
[[19 22]
 [43 50]]


## Euler's Number (e) 
= 2.7182818284590452353602874713527 (and more ...) 
The number e is a famous irrational number, and is one of the most important numbers in mathematics.

For example, the value of (1 + 1/n)n approaches e as n gets bigger and bigger:
n 	(1 + 1/n)n <br>
1 	2.00000 <br>
2 	2.25000 <br>
5 	2.48832 <br>
10 	2.59374 <br>
100 	2.70481 <br>
1,000 	2.71692 <br>
10,000 	2.71815 <br>
100,000 	2.71827 <br>

In [10]:
print(np.exp(1))  # ie. 2.718^2 (2.718 power to 1)
print(np.exp(2))  # ie. 2.718^2
print(np.exp(3))  # ie. 2.718^3

2.718281828459045
7.38905609893065
20.085536923187668


## Implement Sigmoid Function
$sigmoid(x) = \frac{1}{1+e^{-x}}$ is sometimes also known as the logistic function. It is a non-linear function used in Machine Learning (Logistic Regression)and in Deep Learning.

In [11]:
x = np.array([1, 2, 3])
s = 1/(1+np.exp(x*-1))
print(s)

[0.73105858 0.88079708 0.95257413]


## Implement L1 Loss
L1 loss is defined as:
$$\begin{align*} & L_1(\hat{y}, y) = \sum_{i=0}^m|y^{(i)} - \hat{y}^{(i)}| \end{align*}\tag{6}$$
Here, ($ \hat{y} $) = Actual output <br>
y = Expected Output

In [12]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
L1_loss = np.sum(np.abs(np.subtract(y,yhat)))
print(L1_loss)

1.1


## Implement L2 Loss
L2 loss is defined as $$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^m(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}\tag{7}$$

In [13]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
L2_loss = np.sum(np.square(np.subtract(yhat, y)))
print(L2_loss)

0.43
