## Numpy (Numerical Python) Guide for AI, Machine & Deep Learning
Numpy array can only hold elements of same datatype. An array can be 1d, 2d, 3d or nd <br>
**This Notebook will cover the widely used Numpy operations on Vectors and Martices In Artificial Intelligence & Machine Learning.**

This notebook can be used as a reference and handly guide for both newcomers & Experienced in Machine Learning & AI.

**NumPy  Type  C Type  Description** <br> 
np.int8       int8_t    Byte (-128 to 127) <br> 
np.int16  int16_t  Integer (-32768 to 32767) <br>
np.int32  int32_t Integer (-2147483648 to 2147483647) <br> 
np.int64  int64_t Integer (-9223372036854775808 to 9223372036854775807) <br> 
np.uint8  uint8_t  Unsigned integer (0 to 255) <br>
np.uint16  uint16_t  Unsigned integer (0 to 65535) <br>
np.uint32  uint32_t  Unsigned integer (0 to 4294967295) <br> 
np.uint64  uint64_t <br>
Unsigned integer (0 to 18446744073709551615) <br> 
np.intp  intptr_t <br>
Integer used for indexing, typically the same as ssize_t <br>
np.uintp  uintptr_t Integer large enough to hold a pointer <br>
np.float32  float <br>
 
np.float64 / np.float_  double Note that this matches the precision of the builtin python float. <br>
np.complex64  float complex Complex number, represented by two 32-bit floats (real and imaginary components) <br> 
np.complex128 / np.complex_  double complex Note that this matches the precision of the builtin python complex. <br>

## Load Modules

In [1]:
import numpy as np 
print(np.__version__)

1.19.5


# Limitations of List over Numpy Array
You cant apply a mathematicsl operation over complete list but you can apply it on numpy array

In [8]:
distance = [10, 20, 30, 40]
time = [.30, .40, .45, .52]

# speed = distance/time   # gives error
# using numpy array
speed = np.array(distance)/np.array(time)
print(speed)

[33.33333333 50.         66.66666667 76.92307692]


# Appending new element in Array

In [13]:
distance = [10, 20, 30, 40]
distance = distance[0]/2
np.append(distance, 10)

array([ 5., 10.])

## Numpy array Initialization, Access Elements & Slicing
**Note: Array indexing starts from 0 and last element will be n-1**

In [16]:
x = np.array([1,2,3,4,5,6,7,8])

# Numpy array attrinutes
print(f'shape = {x.shape}')
print(f'type = {x.dtype}')    # display datatype
print(f'size = {x.size}')
print(f'dimension = {x.ndim}')   # 1d/2d/3d/nd
# Notice the default elements size is int64

# Set the datatype for stored array elements
x = np.array([1,2,3,4,5,6,7,8], np.int8)
print(x.shape, x.dtype, x.size, x.ndim)  # numpy array attributes

# To access array elements
print(x[0], x[1])
# print(x[10])  # Give out of bound error when try to access element outside of array dimension
print(x[-1]) # Access last element, since array counting starts from 0

# Access Elements based on Range
print(x[0:3])  # prints elements at location from 0 to 2 with a total of 3 elements 
print(x[:4])   # prints elements starts from index 0 till index 4-1 ie. 3
print(x[3:5])  # prints elements from index 3 to index 4
print(x[:])    # prints all elements
print(x[0:6:2]) # prints elements from index 0 till index 5 with a gap of 2.. ie 0th, 2th, 4th

# Creating nD array
y = np.array([[1,2,3],[4,5,6]])     # create 2D array. Notie the 2 starting square brackets
print(y)       
print(f'Datatype={y.dtype}')
print(f'Dimension = {y.ndim}')         # prints the dimension of numpy array
# prints number of bytes in an array. Total 6 elements of size int64. So, 8x6=48 bytes
print(f'Number of bytes={y.nbytes}')   

# Accessing 2D array element
print(y[0,0], y[1,2])
print(y[:,0])     # Access first column
print(y[1,:])     # Access 2nd row 

shape = (8,)
type = int64
size = 8
dimension = 1
(8,) int8 8 1
1 2
8
[1 2 3]
[1 2 3 4]
[4 5]
[1 2 3 4 5 6 7 8]
[1 3 5]
[[1 2 3]
 [4 5 6]]
Datatype=int64
Dimension = 2
Number of bytes=48
1 6
[1 4]
[4 5 6]


## np.shape & np.reshape
**np.shape : Gives the shape of matrix/vector**
**np.reshape: Matrix/vector can be reshaoe to any size based on the no. of elements**

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9])  # convert the passed list to form array
print(x.shape)        # prints shape/dimension of array/vector/matrix
print(f'Dimension = {x.ndim}')         # prints the dimension of numpy array

#Creating n-dimentional Array
x = x.reshape(9,1)    # reshape the array into a row vector
print(x)
print(x.shape)
x = x.reshape(1,9)    # reshape the array into a column vector
print(x)
print(x.shape)
x = x.reshape(3,3)    # reshape into a 3x3 matrix
print(x)
print(x.shape)
print(f'Dimension = {x.ndim}')         # prints the dimension of numpy array

# rows and columns in the shape can be individually accessed as
print(x.shape[0])
print(x.shape[1])

(9,)
Dimension = 1
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(9, 1)
[[1 2 3 4 5 6 7 8 9]]
(1, 9)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
Dimension = 2
3
3


## Copy 1 numpy array into Another

In [ ]:
x = np.array([1,2,3,4,5,6])
y = np.copy(x)
print(x,y)

[1 2 3 4 5 6] [1 2 3 4 5 6]


## Transpose
Flipping a matrix over its diagonal. ie. swapping of rows and colums

In [ ]:
x = np.array([1,2,3,4,5,6])
print(x.T)   # No change since its a 1D array

x=x.reshape(2,3)
print(x)
print(x.T)   # Rows and columns gets swapped

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## Numpy Constants (np.inf, np.NAN, np.e, np.pi...)


In [ ]:
print(np.inf)      # infinity / Positive infinity
print(np.NAN)      # Not A Number
print(np.NINF)     # Negative Infinity 
print(np.PZERO)    # Positive zero
print(np.NZERO)    # Negative zero
print(np.e)        # Euler Number (2.718.....)
print(np.pi)       # 3.14.......

inf
nan
-inf
0.0
-0.0
2.718281828459045
3.141592653589793


## Ones and Zeros Matrix

In [ ]:
#Creating an nD array with Random Values
print(np.empty([3,3])) # Random 3x3 size 2D array/matrix

print(np.zeros([3,3]))  # 3x3 size 2D array/matrix with all zeros

print(np.zeros([2,3,3])) #2x3x3 size 3D array/matrix 

print(np.ones([3,3]))   # 3x3 size 2D array with all ones

print(np.eye(5))        # identical 2d array with 5 one's diagnoally

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## np.arange (similar to python range) & np.linspace

In [ ]:
print(np.arange(10))         # create an array of 10 elements from 0 to 9
print(np.arange(2,10))       # crate an array of elements that starts from 2 and ends before 10
print(np.arange(2,10,3))     # creates an array of elements thats starts from 2 upto 9 with a gap of 3

# Linspace is use to linearly spaced array elements by passing a start number, stop number and total
# numbers to be printed
print(np.linspace(start=0, stop=10, num=10))
print(np.linspace(start=0, stop=20, num=10, dtype=np.int8))

print(np.logspace(0, 10, 10)) # Returns evenly spaced number in log scale


[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 5 8]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[ 0  2  4  6  8 11 13 15 17 20]
[1.00000000e+00 1.29154967e+01 1.66810054e+02 2.15443469e+03
 2.78255940e+04 3.59381366e+05 4.64158883e+06 5.99484250e+07
 7.74263683e+08 1.00000000e+10]


## Random Number Generation using rand, randint, randn

In [ ]:
print(np.random.randint(10))           # Generate a random number less less than the passed value
print(np.random.randint(low=0,high=5)) # Generate a random number between passed low and high value
print(np.random.randint(0, 5))         # same as above
print(np.random.randint(low=0, high=5, size=10)) # Generates 10 random numbers
print(np.random.randint(low=0, high=5, size=10, dtype=np.int8))

print(np.random.rand(10))   # generates 10 floating point positive random numbers
print('\n')
print(np.random.rand(3,3)) # generates 3x3 2D array/matrix of random numbers
print('\n')
# Notice the 3 starrting square brackets in the output. It indicates that it is a 3D matrix
print(np.random.rand(2,3,3)) # generates 2x3x3 3D array/matrix of random numbers
print('\n')
print(np.random.randn(10))  # generates floating point positive and negative random numbers equals to passed parameter


1
0
2
[4 1 1 2 3 0 3 0 4 1]
[4 4 3 2 2 2 4 2 3 2]
[0.47223536 0.85002056 0.86532661 0.60863124 0.88912949 0.16797771
 0.96311123 0.76344502 0.50829524 0.17551505]


[[7.72171859e-01 1.76789591e-01 9.58845594e-02]
 [2.61651373e-04 4.79423096e-01 8.86335600e-01]
 [2.71421188e-01 2.12698209e-01 3.97428393e-01]]


[[[0.25645478 0.45106654 0.45696007]
  [0.95485818 0.94163533 0.62801552]
  [0.74782456 0.06668444 0.63818906]]

 [[0.99700411 0.74621644 0.57611883]
  [0.17869202 0.5362909  0.23102813]
  [0.5765678  0.04853011 0.33412543]]]


[ 0.62698609  0.52990168 -1.7222719   1.03848644  0.71333812 -1.22543441
  0.14547441 -0.84353477 -0.12121542 -2.13987236]


# Flatten any matrix to 1-D Array

### Differences between Flatten() and Ravel()

a.ravel(): <br>
(i) Return only reference/view of original array <br>
(ii) If you modify the array you would notice that the value of original array also changes. <br>
(iii) Ravel is faster than flatten() as it does not occupy any memory. <br>
(iv) Ravel is a library-level function. <br>

a.flatten(): <br>
(i) Return copy of original array <br>
(ii) If you modify any value of this array value of original array is not affected. <br>
(iii) Flatten() is comparatively slower than ravel() as it occupies memory. <br>
(iv) Flatten is a method of an ndarray object. <br>



In [37]:
np.random.seed
x = np.random.randint(0,10,20).reshape(5,4)
print(x)

# Flatten passes copy of original array to 'y' 
y = x.flatten()    # Flatten the matrix to 1D array
print(y)
y[0] = 100
print(x)

# Ravel only passes a view of original array to array 'z'
z = x.ravel()
print(z)
z[0] = 50
print(x)

[[1 6 6 2]
 [2 6 2 8]
 [3 4 5 0]
 [5 9 6 6]
 [9 8 8 5]]
[1 6 6 2 2 6 2 8 3 4 5 0 5 9 6 6 9 8 8 5]
[[1 6 6 2]
 [2 6 2 8]
 [3 4 5 0]
 [5 9 6 6]
 [9 8 8 5]]
[1 6 6 2 2 6 2 8 3 4 5 0 5 9 6 6 9 8 8 5]
[[50  6  6  2]
 [ 2  6  2  8]
 [ 3  4  5  0]
 [ 5  9  6  6]
 [ 9  8  8  5]]


# np.stack to stack 2 arrays 1 over another 
Both arrays should have the same dimension

In [ ]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
z = np.stack((x,y))      # stacking horizontally when axis=0 (default)
print(z)
z = np.stack((x,y), axis=1)  # stacking vertically when axis=1
print(z)

z = np.hstack((x,y))  # stacking horizontally similar to appending
print(z)

x = np.array([1,2,3,4]).reshape(2,2)
y = np.array([5,6,7,8]).reshape(2,2)
z = np.stack((x,y))
print(f'z = {z}')

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[1 2 3 4 5 6 7 8]
z = [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## np.split : Splitting numpy Array into multiple sub-arrays

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(np.split(x, 3))  # split into equal sub arrays
# Split array can be captured as
a,b,c = np.split(x, 3)
print(a,b,c)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3] [4 5 6] [7 8 9]
[9 8 7 6 5 4 3 2 1]


## np.flip : Flipping the array

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(np.flip(x))

x = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(x)
print('\n')
print(f'horizontal flip = \n {np.flip(x)}')        #  flip horizontally
print('\n')
print(f'vertical flip = \n {np.flip(x, axis=1)}')  # flip vertically
print('\n')

[9 8 7 6 5 4 3 2 1]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


horizontal flip = 
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


vertical flip = 
 [[3 2 1]
 [6 5 4]
 [9 8 7]]




## Bitwise Operations

In [ ]:
x = np.array([1,2,3,4])
y = np.array([2,3,1,0])
print(np.bitwise_or(x,y))
print(np.bitwise_and(x,y))
print(np.bitwise_xor(x,y))

x = np.array([1,0,1], np.uint8)
print(np.bitwise_not(x))

[3 3 3 4]
[0 2 1 0]
[3 1 2 4]
[254 255 254]


# Mathematical Operations (+, -, *, /, **) <br> 
# Comparison Operators(>, >=, <, <=, ==, !=) <br> 
# Boolean operations <br>
# Logical operators <br>

In [29]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[arr > 5])
print(arr[arr != 5])

# Boolean operation
arr1 = arr>5  
print(arr1)

print(np.logical_and(arr>3, arr<7))
print(arr[np.logical_and(arr>3, arr<7)])

[6 7 8 9]
[1 2 3 4 6 7 8 9]
[False False False False False  True  True  True  True]
[False False False  True  True  True False False False]
[4 5 6]


## Reshaping of Images
A coloured image is represented by a 3D array of shape (length,height,depth=3) where depth of 3 correponds to R,G, B color. However, when you read an image as the input of an algorithm you need to convert it to a vector of shape **(length∗height∗depth, 1)**. ie. you need to reshape the 3D array into a 1D vector

In [ ]:
# Consider the below image of shape (3,3,3)
image = np.array([[[ 0.67826139,  0.29380381, 0.67826139],
        [ 0.90714982,  0.52835647, 0.90714982],
        [ 0.4215251 ,  0.45017551, 0.4215251]],

       [[ 0.92814219,  0.96677647, 0.92814219],
        [ 0.85304703,  0.52351845, 0.85304703],
        [ 0.19981397,  0.27417313, 0.19981397]],

       [[ 0.60659855,  0.00533165, 0.60659855],
        [ 0.10820313,  0.49978937, 0.10820313],
        [ 0.34144279,  0.94630077, 0.34144279]]])

print(image.shape)
new_shape = image.reshape(image.shape[0]*image.shape[1]*image.shape[2], 1)
print(new_shape)
print(new_shape.shape)

(3, 3, 3)
[[0.67826139]
 [0.29380381]
 [0.67826139]
 [0.90714982]
 [0.52835647]
 [0.90714982]
 [0.4215251 ]
 [0.45017551]
 [0.4215251 ]
 [0.92814219]
 [0.96677647]
 [0.92814219]
 [0.85304703]
 [0.52351845]
 [0.85304703]
 [0.19981397]
 [0.27417313]
 [0.19981397]
 [0.60659855]
 [0.00533165]
 [0.60659855]
 [0.10820313]
 [0.49978937]
 [0.10820313]
 [0.34144279]
 [0.94630077]
 [0.34144279]]
(27, 1)


## Adding a matrix with m rows and 1 column to another with 1 row and 1 column
**A Matrix is defined as a 2D array with Rows & Columns**
So,lets denote number of rows with m and
number of columns with n

**Below are the generalized formula for doing mathematical operation (add, subtract, multiply, divide) on 2 matrices**

Adding a matrix with m row and 1 column to another with 1 row and 1 column will result in adding each row of matrix m with 2nd matrix row
* **(m,1) + (1,1) = (m+1, 1)**
* **(m,1) * (1,1) = (mx1, 1)**
* **(m,1) / (1,1) = (m/1, 1)**
* **(m,1) - (1,1) = (m-1, 1)**

In [ ]:
list1 = [1,2,3,4,5,6]
list2 = [10,20,30]

matrix1 = np.array(list1).reshape(6,1)      # 6 rows and 1 column
print(f"Matrix1 of size m,1 = \n{matrix1}")

matrix2 = np.array(list2[0]).reshape(1,1)
print(f"Matrix2 of size 1,1 = \n{matrix2}")

add_result = np.add(matrix1, matrix2)
print(f"Result m+1,1 = \n{add_result}")

mult_result = np.matmul(matrix1, matrix2)
print(f"Result mx1,1 = \n{mult_result}")

div_result = np.divide(matrix1, matrix2)
print(f"Result m/1,1 = \n{div_result}")

sub_result = np.subtract(matrix1, matrix2)
print(f"Result m-1,1 = \n{sub_result}")

Matrix1 of size m,1 = 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Matrix2 of size 1,1 = 
[[10]]
Result m+1,1 = 
[[11]
 [12]
 [13]
 [14]
 [15]
 [16]]
Result mx1,1 = 
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]
Result m/1,1 = 
[[0.1]
 [0.2]
 [0.3]
 [0.4]
 [0.5]
 [0.6]]
Result m-1,1 = 
[[-9]
 [-8]
 [-7]
 [-6]
 [-5]
 [-4]]


## Adding a matrix with 1 row and n columns to another with 1 row and 1 column
**(1, n) + (1, 1) = (1, n+1)**

In [ ]:
list1 = [1,2,3,4,5,6]
list2 = [10,20,30]

matrix1 = np.array(list1).reshape(1,6)     # 1 row and 6 columns
print(f"Matrix1 of size 1,m = \n{matrix1}")

matrix2 = np.array(list2[0]).reshape(1,1)
print(f"Matrix2 of size 1,1 = \n{matrix2}")

add_result = np.add(matrix1, matrix2)
print(f"Result 1,n+1 = \n{add_result}")

Matrix1 of size 1,m = 
[[1 2 3 4 5 6]]
Matrix2 of size 1,1 = 
[[10]]
Result 1,n+1 = 
[[11 12 13 14 15 16]]


## Adding a matrix with m rows and n columns to another with 1 row and n columns
**(m, n) + (1, n) = (m, n+n)**

In [ ]:
list1 = [1,2,3,4,5,6]
list2 = [10,20,30]

matrix1 = np.array(list1).reshape(2,3)     # 2rows and 3 columns
print(f"Matrix1 of size m,n = \n{matrix1}")

matrix2 = np.array(list2).reshape(1,3)
print(f"Matrix2 of size 1,n = \n{matrix2}")

add_result = np.add(matrix1, matrix2)
print(f"Result m,n+n = \n{add_result}")

Matrix1 of size m,n = 
[[1 2 3]
 [4 5 6]]
Matrix2 of size 1,n = 
[[10 20 30]]
Result m,n+n = 
[[11 22 33]
 [14 25 36]]


## Adding a matrix with m rows and n columns to another with m rows and 1 column
**(m, n) + (m, 1) = (m+m, n)**

In [ ]:
list1 = [1,2,3,4,5,6]
list2 = [10,20,30]

matrix1 = np.array(list1).reshape(3,2)     # 3 rows and 2 columns
print(f"Matrix1 of size m,n = \n{matrix1}")

matrix2 = np.array(list2).reshape(3,1)     # 3 rows and 1 column
print(f"Matrix2 of size 3,1 = \n{matrix2}")

add_result = np.add(matrix1, matrix2)
print(f"Result m+m,n = \n{add_result}")

Matrix1 of size m,n = 
[[1 2]
 [3 4]
 [5 6]]
Matrix2 of size 3,1 = 
[[10]
 [20]
 [30]]
Result m+m,n = 
[[11 12]
 [23 24]
 [35 36]]


## Adding a matrix with m rows and n columns to another with m rows and n columns
Then it will be any of 1 below
* **(m, n) + (m, n) = (m+m, n)**
* **(m, n) + (m, n) = (m, n+n)**
1. Both will have same results

In [ ]:
list1 = [1,2,3,4,5,6]
list2 = [10,20,30,40,50,60]

matrix1 = np.array(list1).reshape(3,2)     # 3 rows and 2 columns
print(f"Matrix1 of size m,n = \n{matrix1}")

matrix2 = np.array(list2).reshape(3,2)     # 3 rows and 2 column
print(f"Matrix2 of size 3,2 = \n{matrix2}")

add_result = np.add(matrix1, matrix2)
print(f"Result m+m,n+n = \n{add_result}")

Matrix1 of size m,n = 
[[1 2]
 [3 4]
 [5 6]]
Matrix2 of size 3,2 = 
[[10 20]
 [30 40]
 [50 60]]
Result m+m,n+n = 
[[11 22]
 [33 44]
 [55 66]]


## Dot (np.dot) multiplication of 2 Vectors & Matrices

In [ ]:
# Dot operation on 2 vectors
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
result = np.dot(x,y)
print(result)   # 1x5 + 2x6 + 3x7 + 4x8 = 70

# Dot operation on 2 matrices
x = np.array([1,2,3,4]).reshape(2,2)
print(f"x = \n{x}")
y = np.array([5,6,7,8]).reshape(2,2)
print(f"y = \n{y}")
result = np.dot(x,y)

# Output calculation (Row X Column):
# 1x5 + 2x7 = 19  ie. row 1 to column 1
# 3x5 + 4x7 = 43  ie. row 2 to column 1
# 1x6 + 2x8 = 22  ie. row 1 to column 2
# 3x6 + 4x8 = 50  ie. row 2 to column 2
print(f"result = \n{result}")   

70
x = 
[[1 2]
 [3 4]]
y = 
[[5 6]
 [7 8]]
result = 
[[19 22]
 [43 50]]


## Euler's Number (e) 
= 2.7182818284590452353602874713527 (and more ...) 
The number e is a famous irrational number, and is one of the most important numbers in mathematics.

For example, the value of (1 + 1/n)n approaches e as n gets bigger and bigger:
n 	(1 + 1/n)n <br>
1 	2.00000 <br>
2 	2.25000 <br>
5 	2.48832 <br>
10 	2.59374 <br>
100 	2.70481 <br>
1,000 	2.71692 <br>
10,000 	2.71815 <br>
100,000 	2.71827 <br>

In [40]:
print(np.exp(1))  # ie. 2.718^2 (2.718 power to 1)
print(np.exp(2))  # ie. 2.718^2
print(np.exp([3,4,5]))  # ie. 2.718^3

arr = [1.4, 3.5, 6.2, 5,9]
print(np.floor(arr))

2.718281828459045
7.38905609893065
[ 20.08553692  54.59815003 148.4131591 ]
[1. 3. 6. 5. 9.]


## Statistical Functions
Variance : The average of the squared differences from the Mean <br>
Standard Deviation : It is just the square root of Variance

In [ ]:
x = np.array([2,4,6,1,8])
print(np.sum(x))
print(np.average(x))
print(np.mean(x))
print(np.var(x))       # variance 
print(np.std(x))       # Standard Deviation 

21
4.2
4.2
2.5612496949731396
6.5600000000000005


## Implement Sigmoid Function
$sigmoid(x) = \frac{1}{1+e^{-x}}$ is sometimes also known as the logistic function. It is a non-linear function used in Machine Learning (Logistic Regression)and in Deep Learning.

In [ ]:
x = np.array([1, 2, 3])
s = 1/(1+np.exp(x*-1))
print(s)

[0.73105858 0.88079708 0.95257413]


## Implement L1 Loss
L1 loss is defined as:
$$\begin{align*} & L_1(\hat{y}, y) = \sum_{i=0}^m|y^{(i)} - \hat{y}^{(i)}| \end{align*}\tag{6}$$
Here, ($ \hat{y} $) = Actual output <br>
y = Expected Output

In [ ]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
L1_loss = np.sum(np.abs(np.subtract(y,yhat)))
print(L1_loss)

1.1


## Implement L2 Loss
L2 loss is defined as $$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^m(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}\tag{7}$$

In [ ]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
L2_loss = np.sum(np.square(np.subtract(yhat, y)))
print(L2_loss)

0.43


## Expand the shape/dimension of an array
It is used in changing the dimension of images in Tensorflow since tensorflow requires a tensor(3D/4D.. array)

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
# mostly used on images to change the dimension in tensorflow
y = np.expand_dims(x, axis=0)  # Add a dimension on 0th position
print(y.shape)

y = np.expand_dims(x,axis=1)   # Add a dimension on 1st position
print(y.shape)

y = np.expand_dims(x,axis=2)   # Add a dimension on 2nd position
print(y.shape)

# y = np.expand_dims(x,axis=3)   # Gives an error  as initial dimension is 2x2 ans we are trying to increase axis on 3rd position
# print(y.shape)

(1, 3, 3)
(3, 1, 3)
(3, 3, 1)
